import { StyleSheet } from "react-native";

export const lightStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: 15,
    paddingTop: 50,
  },
  background: {
    flex: 1,
    backgroundColor: "#64C896",
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  toggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  toggleText: {
    fontSize: 16,
  },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "#f0f0f0",
    padding: 10,
    borderRadius: 20,
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    color: "#333",
    fontSize: 16,
    textAlignVertical: "center",
    includeFontPadding: false,
    lineHeight: 20,
    paddingVertical: 0,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  recentText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#333",
  },
  paperCard: {
    backgroundColor: "#f9f9f9",
    borderRadius: 18,
    padding: 16,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  cardContent: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  paperTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
    textAlign: "left",
    width: "100%",
    lineHeight: 20,
  },
  paperAuthors: {
    fontSize: 14,
    color: "#555",
    marginBottom: 4,
    textAlign: "left",
  },
  paperDate: {
    fontSize: 14,
    color: "#777",
    textAlign: "left",
    marginBottom: 8,
  },
  iconRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "#DDD",
    marginTop: 8,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#57B360",
    paddingVertical: 15,
    position: "absolute",
    bottom: 0,
    width: "110%",
  },
  footerButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  footerText: {
    fontSize: 12,
    marginTop: 5,
    color: "#fff",
  },

  // Comments Modal Styles
  commentsContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "70%",
    backgroundColor: "#f9f9f9",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  commentsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  commentsTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  commentsContent: {
    flex: 1,
  },
  commentItem: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: "#ffffff",
    borderRadius: 10,
  },
  commentAuthor: {
    fontWeight: "bold",
    marginBottom: 5,
    color: "#333",
  },
  commentText: {
    marginBottom: 5,
    color: "#333",
  },
  newCommentContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  commentInput: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: "#888",
    borderRadius: 5,
    backgroundColor: "#fff",
    marginRight: 10,
  },
  addCommentButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#57B360",
    borderRadius: 5,
  },
  addCommentButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
  },

  dateRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  datePickerWrapper: {
    flex: 1,
    minWidth: 0, // Ensures the layout does not expand unexpectedly
    justifyContent: "center",
    marginHorizontal: 2,
  },
  smallDatePicker: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  dateText: {
    marginLeft: 8,
    fontSize: 12,
    color: "#fff",
  },
  applyButton: {
    backgroundColor: "#57B360",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginLeft: 5,
  },
  applyButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  clearButton: {
    backgroundColor: "#2196F3", // Blue for clear button
  },
});

export const darkStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: 15,
    paddingTop: 50,
  },
  background: {
    flex: 1,
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  toggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  toggleText: {
    fontSize: 16,
    color: "#fff",
  },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "#333",
    padding: 10,
    borderRadius: 20,
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    color: "#fff",
    fontSize: 16,
    textAlignVertical: "center",
    includeFontPadding: false,
    lineHeight: 20,
    paddingVertical: 0,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  recentText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#fff",
  },
  paperCard: {
    backgroundColor: "#333333",
    borderRadius: 18,
    padding: 16,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
    overflow: 'hidden',
  },
  cardContent: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  paperTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#EEE",
    marginBottom: 8,
    textAlign: "left",
    lineHeight: 22,
  },
  paperAuthors: {
    fontSize: 14,
    color: "#BBB",
    marginBottom: 4,
    textAlign: "left",
  },
  paperDate: {
    fontSize: 14,
    color: "#AAA",
    textAlign: "left",
    marginBottom: 8,
  },
  iconRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "#555",
    marginTop: 8,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#2B5A3E",
    paddingVertical: 15,
    position: "absolute",
    bottom: 0,
    width: "110%",
  },
  footerButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  footerText: {
    fontSize: 12,
    marginTop: 5,
    color: "#fff",
  },

  // Comments Modal Styles
  commentsContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "70%",
    backgroundColor: "#333333",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  commentsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  commentsTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  commentsContent: {
    flex: 1,
  },
  commentItem: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: "#444444",
    borderRadius: 10,
  },
  commentAuthor: {
    fontWeight: "bold",
    marginBottom: 5,
    color: "#fff",
  },
  commentText: {
    marginBottom: 5,
    color: "#fff",
  },
  newCommentContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  commentInput: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: "#888",
    borderRadius: 5,
    backgroundColor: "#fff",
    marginRight: 10,
  },
  addCommentButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#57B360",
    borderRadius: 5,
  },
  addCommentButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
  },
  dateRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  datePickerWrapper: {
    flex: 1,
    minWidth: 0, // Ensures the layout does not expand unexpectedly
    justifyContent: "center",
    marginHorizontal: 2,
  },
  smallDatePicker: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  dateText: {
    marginLeft: 8,
    fontSize: 12,
    color: "#fff",
  },
  applyButton: {
    backgroundColor: "#57B360",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginLeft: 5,
  },
  applyButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  clearButton: {
    backgroundColor: "#2196F3", // Blue for clear button
  },
  refreshIcon: {
    marginLeft: 10,
    opacity: 1,
  },
  refreshing: {
    opacity: 0.5,
  },
  refreshButton: {
    padding: 8,
    borderRadius: 20,
    marginLeft: 10,
  },
});
